# Generated by Django 3.1.5 on 2021-01-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdSList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdidid', models.IntegerField(db_column='RegDidId')),
                ('cdsid', models.IntegerField(blank=True, db_column='CdSId', null=True)),
                ('academicyear', models.IntegerField(blank=True, db_column='AcademicYear', null=True)),
                ('cdsnameit', models.CharField(blank=True, db_column='CdSNameIT', max_length=255, null=True)),
                ('cdsnameeng', models.CharField(blank=True, db_column='CdSNameENG', max_length=255, null=True)),
                ('departmentid', models.CharField(blank=True, db_column='DepartmentId', max_length=40, null=True)),
                ('departmentnameit', models.CharField(blank=True, db_column='DepartmentNameIT', max_length=255, null=True)),
                ('departmentnameeng', models.CharField(blank=True, db_column='DepartmentNameENG', max_length=255, null=True)),
                ('coursetypeid', models.CharField(blank=True, db_column='CourseTypeId', max_length=10, null=True)),
                ('coursetypename', models.CharField(blank=True, db_column='CourseTypeName', max_length=80, null=True)),
                ('courseclassid', models.CharField(blank=True, db_column='CourseClassId', max_length=10, null=True)),
                ('courseclassname', models.CharField(blank=True, db_column='CourseClassName', max_length=255, null=True)),
                ('cdslanguageit', models.CharField(blank=True, db_column='CdsLanguageIT', max_length=100, null=True)),
                ('cdslanguageeng', models.CharField(blank=True, db_column='CdSLanguageENG', max_length=100, null=True)),
                ('cdsduration', models.IntegerField(blank=True, db_column='CdSDuration', null=True)),
                ('cdsects', models.IntegerField(blank=True, db_column='CdSECTS', null=True)),
                ('cdsattendance', models.IntegerField(blank=True, db_column='CdSAttendance', null=True)),
                ('jointdegree', models.CharField(blank=True, db_column='JointDegree', max_length=100, null=True)),
            ],
            options={
                'db_table': 'CDSLIST',
                'managed': False,
            },
        ),
    ]
