# Generated by Django 3.1.5 on 2021-01-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0005_auto_20200912_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidatticaDipartimento',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('dip_id', models.IntegerField(db_column='DIP_ID', primary_key=True, serialize=False)),
                ('dip_cod', models.CharField(blank=True, db_column='DIP_COD', max_length=40, null=True)),
                ('dip_des_it', models.CharField(blank=True, db_column='DIP_DES_IT', max_length=255, null=True)),
                ('dip_des_eng', models.CharField(blank=True, db_column='DIP_DES_ENG', max_length=255, null=True)),
                ('dip_nome_breve', models.CharField(blank=True, db_column='DIP_NOME_BREVE', max_length=100, null=True)),
                ('dip_cd_csa', models.CharField(blank=True, db_column='DIP_CD_CSA', max_length=40, null=True)),
                ('miur_dip_id', models.IntegerField(blank=True, db_column='MIUR_DIP_ID', null=True)),
                ('url_pubbl_off_f', models.CharField(blank=True, db_column='URL_PUBBL_OFF_F', max_length=255, null=True)),
                ('dip_vis_web_flg', models.IntegerField(blank=True, db_column='DIP_VIS_WEB_FLG', null=True)),
            ],
            options={
                'verbose_name_plural': 'Dipartimento',
                'db_table': 'DIDATTICA_DIPARTIMENTO',
            },
        ),
        migrations.CreateModel(
            name='TerritorioIT',
            fields=[
                ('cd_catasto', models.CharField(db_column='CD_CATASTO', max_length=255, primary_key=True, serialize=False)),
                ('cd_istat', models.CharField(blank=True, db_column='CD_ISTAT', max_length=6, null=True)),
                ('cd_sigla', models.CharField(blank=True, db_column='CD_SIGLA', max_length=2, null=True)),
                ('cd_770_regio', models.CharField(blank=True, db_column='CD_770_REGIO', max_length=2, null=True)),
                ('ds_comune', models.CharField(blank=True, db_column='DS_COMUNE', max_length=255, null=True)),
                ('ds_provincia', models.CharField(blank=True, db_column='DS_PROVINCIA', max_length=255, null=True)),
                ('ds_regione', models.CharField(blank=True, db_column='DS_REGIONE', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Territorio',
                'db_table': 'TERRITORIO_IT',
            },
        ),
    ]
